### ISSUE TITLE
im getting this error with geysermodelengine and geyser plugin

### ISSUE THREAD

**Issue by anthony114669** [GeyserExtensionists/GeyserModelEngine#18]
[10:27:20 ERROR]: [org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event  for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.IllegalArgumentException: Command cannot be bedrockOnly if it is not playerOnly
        at Geyser-Spigot.jar/org.geysermc.geyser.command.GeyserCommand.<init>(GeyserCommand.java:107) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.extension.command.GeyserExtensionCommand.<init>(GeyserExtensionCommand.java:57) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.extension.command.GeyserExtensionCommand$Builder$1.<init>(GeyserExtensionCommand.java:187) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.extension.command.GeyserExtensionCommand$Builder.build(GeyserExtensionCommand.java:187) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.extension.command.GeyserExtensionCommand$Builder.build(GeyserExtensionCommand.java:75) ~[Geyser-Spigot.jar:?]
        at me.zimzaza4.geyserutils.geyser.GeyserUtils.onLoadCommand(GeyserUtils.java:224) ~[?:?]
        at Geyser-Spigot.jar/org.lanternpowered.lmbda.Lmbda$4.accept(Unknown Source) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.command.CommandRegistry.<init>(CommandRegistry.java:163) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.command.CommandRegistry.<init>(CommandRegistry.java:106) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.command.SpigotCommandRegistry.<init>(SpigotCommandRegistry.java:45) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:211) ~[Geyser-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by otDan** [comment]
this is not a geysermodelengine error but geyserutils
