### ISSUE TITLE
Im not sure i installed correctly but...

### ISSUE THREAD

**Issue by rise2477** [GeyserExtensionists/GeyserModelEngine#25]
I install
Velocity:
GeyserVelocity
- extension
  - geyserutil geyser
  - geysermodelenginepackgenerator
Backend:
GeyserModelENgine
geyserutil spigot

I found this error in velocity folder

```
[14:51:13 ERROR] [org.geysermc.geyser.event.GeyserEventBus]: An exception occurred while executing event GeyserPostInitializeEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoSuchFieldError: Class org.geysermc.geyser.registry.Registries does not have member field 'org.geysermc.geyser.registry.SimpleDeferredRegistry BEDROCK_ENTITY_IDENTIFIERS'
        at me.zimzaza4.geyserutils.geyser.GeyserUtils.registerEntityToGeyser(GeyserUtils.java:209) ~[?:?]
        at me.zimzaza4.geyserutils.geyser.GeyserUtils.onEnable(GeyserUtils.java:120) ~[?:?]
        at org.lanternpowered.lmbda.Lmbda$27.accept(Unknown Source) ~[server.jar:3.4.0-SNAPSHOT (git-5e397f2b)]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[?:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[?:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[?:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:647) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:265) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:870) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onGeyserEnable(GeyserVelocityPlugin.java:144) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onProxyBound(GeyserVelocityPlugin.java:209) ~[?:?]
        at org.geysermc.geyser.platform.velocity.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.4.0-SNAPSHOT (git-5e397f2b)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:527) ~[server.jar:3.4.0-SNAPSHOT (git-5e397f2b)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:516) ~[server.jar:3.4.0-SNAPSHOT (git-5e397f2b)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by zimzaza4** [comment]
UPDATE YOUR GEYSER

**Comment by zimzaza4** [comment]
and don't forget install GeyserUtils-Velocity for Velocity
