### ISSUE TITLE
on Standalone no working

### ISSUE THREAD

**Issue by SonnenPingu** [GeyserExtensionists/GeyserModelEngine#27]
6M -jar geyser.jar
[19:23:17 INFO] Loading extensions...
[19:23:17 WARN] The extension GeyserUtils requested the Base API version 1.0.0, which is deprecated in favor of specifying the Geyser API version. Please update the extension, or contact its developer.
[19:23:18 ERROR] Couldn't load GeyserModelEngine-1.0-SNAPSHOT.jar in folder /home/container/extensions/GeyserModelEngine-1.0-SNAPSHOT.jar:
org.geysermc.geyser.api.extension.exception.InvalidDescriptionException: Failed to load extension description for /home/container/extensions/GeyserModelEngine-1.0-SNAPSHOT.jar
        at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:128) ~[geyser.jar:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.lambda$loadAllExtensions$0(GeyserExtensionLoader.java:180) ~[geyser.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.loadAllExtensions(GeyserExtensionLoader.java:168) [geyser.jar:?]
        at org.geysermc.geyser.api.extension.ExtensionManager.loadAllExtensions(ExtensionManager.java:88) [geyser.jar:?]
        at org.geysermc.geyser.extension.GeyserExtensionManager.init(GeyserExtensionManager.java:48) [geyser.jar:?]
        at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:215) [geyser.jar:?]
        at org.geysermc.geyser.GeyserImpl.load(GeyserImpl.java:863) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:225) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:172) [geyser.jar:?]
Caused by: java.nio.file.NoSuchFileException: /extension.yml
        at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:861) ~[jdk.zipfs:?]
        at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:751) ~[jdk.zipfs:?]
        at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:270) ~[jdk.zipfs:?]
        at java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
        at java.nio.file.Files.newBufferedReader(Files.java:2897) ~[?:?]
        at java.nio.file.Files.newBufferedReader(Files.java:2930) ~[?:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:124) ~[geyser.jar:?]
        ... 10 more
[19:23:18 WARN] The extension GeyserModelEnginePackGenerator requested the Base API version 1.0.0, which is deprecated in favor of specifying the Geyser API version. Please update the extension, or contact its developer.

**Comment by SonnenPingu** [comment]
^^
